#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dssi
Version  : 1.1.1
Release  : 1
URL      : https://sourceforge.net/projects/dssi/files/dssi/1.1.1/dssi-1.1.1.tar.gz
Source0  : https://sourceforge.net/projects/dssi/files/dssi/1.1.1/dssi-1.1.1.tar.gz
Summary  : An API for audio processing plugins & softsynths with UIs
Group    : Development/Tools
License  : LGPL-2.1
Requires: dssi-bin = %{version}-%{release}
Requires: dssi-lib = %{version}-%{release}
Requires: dssi-license = %{version}-%{release}
Requires: dssi-man = %{version}-%{release}
BuildRequires : buildreq-kde
BuildRequires : ladspa_sdk-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(sndfile)

%description
DSSI
----
This is the DSSI Soft Synth Interface specification & example
code repository.

%package bin
Summary: bin components for the dssi package.
Group: Binaries
Requires: dssi-license = %{version}-%{release}

%description bin
bin components for the dssi package.


%package dev
Summary: dev components for the dssi package.
Group: Development
Requires: dssi-lib = %{version}-%{release}
Requires: dssi-bin = %{version}-%{release}
Provides: dssi-devel = %{version}-%{release}
Requires: dssi = %{version}-%{release}
Requires: dssi = %{version}-%{release}

%description dev
dev components for the dssi package.


%package lib
Summary: lib components for the dssi package.
Group: Libraries
Requires: dssi-license = %{version}-%{release}

%description lib
lib components for the dssi package.


%package license
Summary: license components for the dssi package.
Group: Default

%description license
license components for the dssi package.


%package man
Summary: man components for the dssi package.
Group: Default

%description man
man components for the dssi package.


%prep
%setup -q -n dssi-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560103933
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1560103933
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dssi
cp COPYING %{buildroot}/usr/share/package-licenses/dssi/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dssi_analyse_plugin
/usr/bin/dssi_list_plugins

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/pkgconfig/dssi.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/dssi/karplong.so
/usr/lib64/dssi/less_trivial_synth.so
/usr/lib64/dssi/trivial_sampler.so
/usr/lib64/dssi/trivial_synth.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dssi/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dssi_analyse_plugin.1
/usr/share/man/man1/dssi_list_plugins.1
/usr/share/man/man1/dssi_osc_send.1
/usr/share/man/man1/dssi_osc_update.1
/usr/share/man/man1/jack-dssi-host.1
